FROM node:18 as development

WORKDIR /app

COPY package*.json ./

RUN npm install 

RUN npm i @nestjs/cli --save

RUN npm install --save @nestjs/typeorm typeorm

RUN npm install pg --save

COPY . .

RUN npm run build